var Cambrian = Cambrian || {};
Cambrian.pollApp = Cambrian.pollApp || {};

var templateData = [
  { 
    id: "UUID101",
    type: "Battle Ping",
    title: "Join Operation Red Dawn! Bring Ships!",
    description: "We are going to burn the Russian Starbase. Scythe/Moa fleet is leaving at 21:00 from V-3.",
    options: [{text: "I'll be there"}, {text: "I can't go"}],
    allowMultipleChoices: false,
    allowComments: false,
    dismissText: "Dismiss",
    submitText: "Submit",
  },
  { 
    id: "UUID102",
    type: "Poll",
    title: "What is your favorite Snack?",
    description: "We are about to restock the vending machine and want to know what y'all want in it.",
    options: [{text: "Tortrix BBQ"}, {text: "Tortrix Crema Agria"}, {text: "Lays BBQ"}, {text: "Lays Original"}],
    allowMultipleChoices: false,
    allowComments: false,
    dismissText: "Dismiss",
    submitText: "Submit",
  },
  { 
    id: "UUID103",
    type: "Vote",
    title: "Leonardo di Cambrian for President of the Organization",
    description: "Vote for me, I promise I won't do anything evil.",
    options: [{text: "Vote Yes"}, {text: "Vote No"}],
    allowMultipleChoices: false,
    allowComments: false,
    dismissText: "Dismiss",
    submitText: "Submit",
  },
  { 
    id: "UUID104",
    type: "LocalTrader",
    title: "I have 2 BTC to sell immediately. Takers?",
    description: "bitstamp +5%",
    options: [{text: "Yes, I'll buy BTC now"}],
    allowMultipleChoices: false,
    allowComments: false,
    dismissText: "Dismiss",
    submitText: "Submit",
  },
  { 
    id: "UUID105",
    type: "Community",
    title: "Swarm protest at 1pm. Can you join?",
    description: "Location and slogans are opsec, we'll tell you if you commit to joining.",
    options: [{text: "Yes, I can join"}, {text: "Yes, I can join and bring my megaphone"}, {text: "No, but good luck!"}, {text: "No way. Swarm Rules!"}],
    allowMultipleChoices: false,
    allowComments: false,
    dismissText: "Dismiss",
    submitText: "Submit",
  },
]

var exampleTemplateData = [
  { 
    id: "UUID201",
    type: "Battle Ping",
    title: "Join Operation Red Dawn! Bring Ships!",
    description: "We are going to burn the Russian Starbase. Scythe/Moa fleet is leaving at 21:00 from V-3.",
    options: [{text: "I'll be there"}, {text: "I can't go"}],
    allowMultipleChoices: false,
    allowComments: false,
    dismissText: "Dismiss",
    submitText: "Submit",
  },
  { 
    id: "UUID202",
    type: "Vote",
    title: "President of the Organization",
    description: "Who should be made President for Life?",
    options: [{text: "Voodoo"}, {text: "Hiro"}, {text: "Plato"}, {text: "Rafael"}, {text: "Dan"}, {text: "Ceasar"}],
    allowMultipleChoices: false,
    allowComments: false,
    dismissText: "Dismiss",
    submitText: "Submit",
  },
  { 
    id: "UUID203",
    type: "Poll",
    title: "What should we call the new product geared toward developer teams?",
    description: "We need a snappy name for the new time management tool.",
    options: [{text: "The Whippenator"}, {text: "Iron Maiden"}, {text: "The Rack"}],
    allowMultipleChoices: false,
    allowComments: false,
    dismissText: "Dismiss",
    submitText: "Submit",
  },
  { 
    id: "UUID204",
    type: "Opinion",
    title: "Does Gavin have the skills and vision to lead the developer team?",
    description: "Well, does he?",
    options: [{text: "Yes"}, {text: "no"}],
    allowMultipleChoices: false,
    allowComments: false,
    dismissText: "Dismiss",
    submitText: "Submit",
  },
  { 
    id: "UUID205",
    type: "Help",
    title: "Can someone please help me install the latest version of the software?",
    description: "I keep getting missing dependencies errors.",
    options: [{text: "Yes, I can help the noob"}],
    allowMultipleChoices: false,
    allowComments: false,
    dismissText: "Dismiss",
    submitText: "Submit",
  },
  { 
    id: "UUID206",
    type: "Emergency",
    title: "Tsunami has subsided. Who can help bring these supplies?",
    description: "We need supplies from your warehouses at the rally point.",
    options: [{text: "I can bring water (# pallets in comments)"}, {text: "I can bring blankets (# comments)"}, {text: "I can bring batteries (#/types in comments)"}, {text: "I can bring MREs (# pallets in comments)"}],
    allowMultipleChoices: true,
    allowComments: true,
    dismissText: "Dismiss",
    submitText: "Submit",
  },
]

Cambrian.pollApp.mockTemplates = templateData;
Cambrian.pollApp.exampleTemplates = exampleTemplateData;